// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqAPbhyRK3pVMd5Sm24DOP2lL6C_sCh2Q',
    appId: '1:997028233706:android:973a82745a4b1e67d9b293',
    messagingSenderId: '997028233706',
    projectId: 'donation-platform-93504',
    databaseURL: 'https://donation-platform-93504-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donation-platform-93504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkt_-XmMGTT_zs0rkgXig_Kac6BRNI1NA',
    appId: '1:997028233706:ios:197199c69b927710d9b293',
    messagingSenderId: '997028233706',
    projectId: 'donation-platform-93504',
    databaseURL: 'https://donation-platform-93504-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donation-platform-93504.appspot.com',
    iosBundleId: 'com.ynvdonationplatform.ynvDonationPlatform',
  );
}
